class AppString {
  static const String loginWithInstagram = 'loginWithInstagram';
  static const String appName = 'appName';
  static const String loginHeader = 'loginHeaderİ';
  static const String loginInformation = 'loginInformation';
  static const String loginContract = 'loginContract';
  static const String unExpectedErrorOccurred = 'unExpectedErrorOccurred';
  static const String nullResultAuthentication = 'nullResultAuthentication';
  static const String nullResultInfo = 'nullResultInfo';
  static const String nullResultFriend = 'nullResultFriend';
  
  static const String followers = 'followers';
  static const String following = 'following';
  static const String averageLikes = 'averageLikes';
  static const String posts = 'posts';
  static const String averageComment = 'averageComment';
  static const String earnedFollowers = 'earnedFollowers';
  static const String followersNotFollowing = 'followersNotFollowing';
  static const String fans = 'fans';
  static const String friends = 'friends';
  static const String lostFollowers = 'lostFollowers';
  static const String audience = 'audience';
  static const String mostCommentedPost = 'mostCommentedPost';
  static const String mostLikedPost = 'mostLikedPost';
  static const String lessCommentedPost = 'lessCommentedPost';
  static const String lessLikedPost =     'lessLikedPost';
  static const String follow = 'follow';
  static const String unfollow='unfollow';
  static const String ok = 'ok';
  static const String yes = 'yes';
  static const String no = 'no';
  static const String cancel = 'cancel';
  static const String warning = 'warning';
  static const String error = 'error';
  static const String information = 'information';
  static const String question = 'question';
  static const String message = 'message';
  static const String loading = 'loading';
}
